### ISSUE TITLE
ImportError generated when run in simple program

### ISSUE THREAD

**Issue by tgundersen11** [CDonnerer/xgboost-distribution#23]
I've run the following file in my terminal:

```
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split

from xgboost_distribution import XGBDistribution


if __name__ == '__main__':
    data = load_boston()
    X, y = data.data, data.target
    X_train, X_test, y_train, y_test = train_test_split(X, y)

    model = XGBDistribution(
        distribution="normal",
        n_estimators=500
    )
    model.fit(
        X_train, y_train,
        eval_set=[(X_test, y_test)],
        early_stopping_rounds=10
    )
```

This produce an import error when it is ran: 

```
Traceback (most recent call last):
  File "test_1.py", line 4, in <module>
    from xgboost_distribution import XGBDistribution
  File "/Users/user1/opt/anaconda3/lib/python3.8/site-packages/xgboost_distribution/__init__.py", line 18, in <module>
    from xgboost_distribution.model import XGBDistribution  # noqa
  File "/Users/user1/opt/anaconda3/lib/python3.8/site-packages/xgboost_distribution/model.py", line 7, in <module>
    from xgboost.sklearn import XGBModel, _wrap_evaluation_matrices, xgboost_model_doc
ImportError: cannot import name '_wrap_evaluation_matrices' from 'xgboost.sklearn' (/Users/user1/opt/anaconda3/lib/python3.8/site-packages/xgboost/sklearn.py)
```

sklearn modules are all fully updated, as well as those than sklearn requires. Why could this error be happening?

**Comment by CDonnerer** [comment]
Could you please check and/or update the version of `xgboost`?

E.g. `pip install "xgboost>=1.4.0"`

**Comment by tgundersen11** [comment]
This was returned after typing that command in terminal, so I am definitely already updated to at least 1.4.0. 
```
Requirement already satisfied: xgboost>=1.4.0 in /Users/timgundersen/opt/anaconda3/lib/python3.8/site-packages (1.4.2)
Requirement already satisfied: numpy in /Users/timgundersen/opt/anaconda3/lib/python3.8/site-packages (from xgboost>=1.4.0) (1.20.3)
Requirement already satisfied: scipy in /Users/timgundersen/opt/anaconda3/lib/python3.8/site-packages (from xgboost>=1.4.0) (1.7.0)
```

Is it possible that this is an error out of my control?

**Comment by CDonnerer** [comment]
This should work then (and indeed does in CI). You might be inadvertently running the script from a different python environment, i.e. not the one `/Users/user1/opt/anaconda3/lib/python3.8/`, you could try something like `which python` to check and/or use the anaconda docs.

**Comment by tgundersen11** [comment]
Should work but then yet again it doesn't, haha...
```
(base) timgundersen@Tims-MacBook-Pro testing_week6 % which python
/Users/timgundersen/opt/anaconda3/bin/python
```
Python is definitely fully updated. @CDonnerer
